name: generic_search_bar
description: A new handsome Generic Search Bar for Flutter Package.
# publish_to: 'none'
version: 0.0.1
author: Yalım Erdem<yalim.erdem@picksoft.com.tr>
homepage: https://github.com/YlmRdm/generic_search_bar.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.7.0
  flutter_staggered_grid_view: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: